### ISSUE TITLE
Game doesn't print 'Help' 

### ISSUE THREAD

**Issue by Parkwill** [mserdarsanli/freecell#1]
Even I press F1, Help window doesn't be output. Everything else is fine.

OS : Ubuntu 18.04.3 LTS 64bit
Processor : AMD Ryzen 3500u

**Comment by mserdarsanli** [comment]
Thanks for the report, I pushed [commit 2402c9f](
https://github.com/mserdarsanli/freecell/commit/2402c9f8492a824cce6470044677215fe7790faa) which fixed it for me (gnome terminal on linux mint)

**Comment by Parkwill** [comment]
Ohh! It works well. :)
